queue_rules:
  - name: default
    queue_conditions:
      - label!=no-mergify
      - -draft
      - approved-reviews-by=@fedora-infra/fedora-infrastructure-developers
      - "#changes-requested-reviews-by=0"
      - check-success=Misc tests (lint)
      - check-success=Misc tests (format)
      - check-success=Misc tests (security)
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)
      - check-success=Unit tests (flask1)
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Misc tests (lint)
      - check-success=Misc tests (format)
      - check-success=Misc tests (security)
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)
      - check-success=Unit tests (flask1)
    merge_method: rebase

pull_request_rules:

  - name: Merge pre-commit autoupdates
    actions:
      merge:
        method: rebase
    conditions:
      - label!=no-mergify
      - -draft
      - author=github-actions[bot]
      - title=Auto-update pre-commit hooks
      - "#changes-requested-reviews-by=0"
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
